version: '2'
services:
    simplemdedemoapp-app:
        image: simplemdedemoapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://simplemdedemoapp-mysql:3306/simplemdedemoapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simplemdedemoapp-mysql:
        extends:
            file: mysql.yml
            service: simplemdedemoapp-mysql
